# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ModelService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ModelService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ModelService.proto\x12\x0f\x63om.grpc.client\"F\n\x0fPerformanceData\x12\x33\n\x0fhistorical_data\x18\x01 \x03(\x0b\x32\x1a.com.grpc.client.DataPoint\"G\n\tDataPoint\x12\x12\n\nmerge_size\x18\x01 \x01(\x05\x12\x12\n\nthread_num\x18\x02 \x01(\x05\x12\x12\n\nthroughput\x18\x03 \x01(\x01\"R\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12/\n\nprediction\x18\x02 \x01(\x0b\x32\x1b.com.grpc.client.Prediction\"a\n\nPrediction\x12\x1a\n\x12optimal_merge_size\x18\x01 \x01(\x05\x12\x1a\n\x12optimal_thread_num\x18\x02 \x01(\x05\x12\x1b\n\x13\x65xpected_throughput\x18\x03 \x01(\x01\x32l\n\x0cModelService\x12\\\n\x15UpdatePerformanceData\x12 .com.grpc.client.PerformanceData\x1a\x1f.com.grpc.client.UpdateResponse\"\x00\x42&\n\x0f\x63om.grpc.clientB\x11ModelServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ModelService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.grpc.clientB\021ModelServiceProtoP\001'
  _globals['_PERFORMANCEDATA']._serialized_start=39
  _globals['_PERFORMANCEDATA']._serialized_end=109
  _globals['_DATAPOINT']._serialized_start=111
  _globals['_DATAPOINT']._serialized_end=182
  _globals['_UPDATERESPONSE']._serialized_start=184
  _globals['_UPDATERESPONSE']._serialized_end=266
  _globals['_PREDICTION']._serialized_start=268
  _globals['_PREDICTION']._serialized_end=365
  _globals['_MODELSERVICE']._serialized_start=367
  _globals['_MODELSERVICE']._serialized_end=475
# @@protoc_insertion_point(module_scope)
